[package]
name = "hd_quicksilver"
readme = "README.md"
description = "high-degree quicksilver ZK proofs"
categories = ["cryptography"]
keywords = ["cryptography", "zero-knowledge", "circuit"]
autoexamples = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[features]
ff = ["scuttlebutt/ff"]

[dependencies]
blake3.workspace = true
rand.workspace = true
eyre.workspace = true
generic-array.workspace = true
log.workspace = true
scuttlebutt.workspace = true
smallvec.workspace = true
subtle.workspace = true
ocelot.workspace = true
serde.workspace = true